- name: Copy the script
  become: yes
  ansible.builtin.copy:
    src: install-newrelic-infra.sh
    dest: /root/
    owner: root
    group: wheel
    mode: '0755'  

- name: Install newrelic-infra agent
  ansible.builtin.shell: /root/install-newrelic-infra.sh
  args:
    executable: /bin/bash
  become: yes  

- name: Remove script
  ansible.builtin.file:
    path: /root/install-newrelic-infra.sh
    state: absent
  become: yes  

- name: Set newrelic key
  lineinfile:
    path: /etc/newrelic-infra.yml
    regexp: '^license_key: '
    line: license_key: test