  - name: Install apache
    ansible.builtin.package:
      name: nginx
      state: latest
    become: True

  - name: Start nginx service
    systemd:
      state: started
      name: nginx   

  - name: Install apache
    ansible.builtin.package:
      name: postfix
      state: latest
    become: True