  - name: Install apache
    package:
      name: nginx
      state: latest
    become: True

  - name: Start apache service
    systemd:
      state: started
      name: nginx

  - name: Sites Enabled links
    file:
      dest: /home/ec2-user/link
      state: link
      src: /home/ec2-user/*          
