---
- name: Write hostname
  hosts: "{{ hosts | default('all') }}"

  tasks:
  - name: write hostname using jinja2
    ansible.builtin.template:
       src: templates/test.j2
       dest: /home/ec2-user/hostname
